### ISSUE TITLE
This project appears to introduce 896 files via itself and its deps

### ISSUE THREAD

**Issue by stefanpenner** [rickharrison/broccoli-asset-rev#101]
own outliers

* tests 199, I suspect we do not want to include tests in published NPM releases.

deps:

- [x] broccoli-asset-rewrite 110
- [x] broccoli-filter 470
- [x] json-stable-stringify 30
- [x] matcher-collection 35
- [x]  rsvp 39

**Comment by twokul** [comment]
@stefanpenner unsure we can do much about `rsvp` but the rest of them are patched
