### ISSUE TITLE
Fingerprints protocol relative URLs

### ISSUE THREAD

**Issue by felixbuenemann** [rickharrison/broccoli-asset-rev#106]
broccoli-asset-rev@2.4.6 wrongly fingerprints protocol relative URLs:

input:

```html
<img src="//cdn.example.com/foo.png" />
```

output:

```html
<img src="//cdn.example.com/foo-ff90e8722fb1fb8000e1b6533589ce90.png" />
```

expected:

```html
<img src="//cdn.example.com/foo.png" />
```

I also tried to exclude the protocol relative urls using the following config, but it doesn't work, the urls are still fingerprinted:

```javascript
// ember-cli-build.js
var app = new EmberApp({
  fingerprint: {
    exclude: ['//**']
  }
});
```

**Comment by felixbuenemann** [comment]
This also happens with non relative URLs. Is this expected behavior?

I found a similar report in rickharrison/broccoli-asset-rewrite#24.

**Comment by felixbuenemann** [comment]
Sorry, seems this report should've gone to broccoli-asset-rewrite. I was confused because the ember docs mention this plugin in the section on fingerprinting and the configuration is shared for both broccoli-asset-rev and broccoli-asset-rewrite.

**Comment by rickharrison** [comment]
Why is this wrong behavior? It is an asset, hence why it's fingerprinted.
