### ISSUE TITLE
Uncaught ReferenceError: define is not defined

### ISSUE THREAD

**Issue by nag9329** [rickharrison/broccoli-asset-rev#107]
I'm working with ember-cli and I just copied the two lines into ember-cli-build.js file as below 
var app = new EmberApp(defaults, {
	fingerprint:{
		enabled:true
	}
  });

Then I'm getting the following error: define is not defined in my application.js file and if I remove the above code, I'm able to run my project successfully. But, I want to append the hash code to all of my assets. 

The above code does hashing and appends to all of my files vendor.css,vendor.js, project-name.css,project-name.js in the dist folder but I cannot run the project because of the error. I've researched a lot about this, but nobody is facing this problem.

**Comment by rickharrison** [comment]
I'm sorry, but I am not sure what your issue is. I'd recommend posting this question on stackoverflow.com with an ember tag

**Comment by nag9329** [comment]
Posted a question on stackoverflow.com but can you see what exactly is going on here. 
All I'm doing is adding the two lines fingerprint:{enabled:true} in my ember-cli-build.js file, then I'm getting the uncaught reference error: define is not defined in all my javascript files. Am I using the plugin in the right way or am I missing anything? I've been on this issue since 2 days and I'm wondering no one else got this issue

**Comment by rickharrison** [comment]
Unfortunately, I am not familiar with ember cli any longer. I would try asking in some of the community options found on https://github.com/ember-cli/ember-cli
