### ISSUE TITLE
replaceExtensions not working with php

### ISSUE THREAD

**Issue by NicholasJohn16** [rickharrison/broccoli-asset-rev#109]
I've added `php` to the `replaceExtensions`, but when I do a production build, the filenames aren't being replaced with the checksums. 

```
module.exports = function(defaults) {
  var env = EmberApp.env();
  var isProduction = env === 'production';

  var app = new EmberApp(defaults, {
    fingerprint : {
        replaceExtensions : [ 'html', 'php', 'css', 'js' ]
    },
    outputPaths: {
      app: {
        html: isProduction ? 'default.php' : 'index.html',
        css: {
          'app': '/media/application-name.css'
        },
        js: '/media/application-name.js'
      },
      vendor: {
        css: '/media/com_stonewall/vendor.css',
        js: '/media/com_stonewall/vendor.js'
      }
    }
}
```

Am I missing something?

EDIT: This actually looks like a problem with using different outputPaths, as when I remove them it works properly. Is there a way to include fingerprinting with different paths?

**Comment by rickharrison** [comment]
Are the php files included in the tree sent to the ember application? If you could contribute a failing test, it would be easier for me to figure this out for you.

**Comment by rickharrison** [comment]
Closing for now as the extensions are a complete abstraction and I don't see why one extension would work over another. Please provide any additional information and I will re-open.
