### ISSUE TITLE
[Question] How can I use fingerprint for svg file inside my addon?

### ISSUE THREAD

**Issue by kaermorchen** [rickharrison/broccoli-asset-rev#124]
Hello. I am sorry for my English.

I create addon for store svg icons in one file. Template of icon component generate this code:

```
<svg viewBox="0 0 24 24" width="24" height="24" role="img" class="mdi-icon ember-view">
   <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/icons.svg#bug"></use>
</svg>
```

But fingerprint don't work with `/assets/icons.svg`. You can see it on the [demo](https://kaermorchen.github.io/ember-mdi/).

I read about [options](https://github.com/rickharrison/broccoli-asset-rev#default-settings) and [using](https://github.com/rickharrison/broccoli-asset-rev#ember-cli-addon-usage) but it for EmberApp.

How can I turn on fingerprint for svg file by default inside addon?

**Comment by st-h** [comment]
@kaermorchen broccoli asset rev does not include svg files in its default file pattern. You'll need to add something like this to `ember-cli-build.js`:
```
fingerprint: {
  extensions: ['js', 'css', 'png', 'jpg', 'gif', 'map', 'svg']
},
```

**Comment by kaermorchen** [comment]
Thank you
