### ISSUE TITLE
ember-cli Handlebars templates not using fingerprinted assets

### ISSUE THREAD

**Issue by josh-padnick** [rickharrison/broccoli-asset-rev#14]
Hello, I'm using `ember-cli`, but running `ember build environment=production` does not rename certain images in my source file to match the updated fingerprinted name.  Here's how to reproduce:

**Brocfile.js**

```
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp({
    fingerprint: {
        replaceExtensions: ['html', 'css', 'js']
    }
});
```

The image itself is referenced in my Handlebars template:

**/app/templates/standard-shell.hbs**

``` html
<a class="navbar-brand" href="#"><img class="logo" src="assets/images/logo-white.png" /></a>
```

After running `ember build environment=production`, when I look in `/dist/assets/images`, I see a file `logo-white-2f70fda5e0c5b1069f090e573fff37a5.png` that is fingerprinted as expected.

But when I load the ember app, it's still referencing `assets/images/logo-white.png`. Is this plugin not meant to work with Handlebars templates, or did I miss anything in my setup process?

Thanks for writing this and for your input!

**Update:** I also want to add that a `.jpg` file on the same page is converting to fingerprinted URL just fine.  Even placing the PNG elsewhere in the page doesn't seem to change things.

**Update 2:** The actual file name I'm using is `omedix-engage-logo.png`. Even after removing `png` from the list of `extensions`, I'm noticing that the tool still converts the file name to `OMEDIX-engage-logo.png` (note the caps).  Seems like a bug.

**Comment by ggstuart** [comment]
This got me too. I'm developing on windows and deploying on debian. Thanks to this thread I tracked it down.
