### ISSUE TITLE
Change in template files does not result in a change in the cheksum

### ISSUE THREAD

**Issue by rduque1** [rickharrison/broccoli-asset-rev#36]
Hi,
In my index.hbs i did some changes and build again, but all the checksums stay the same in the dist/index.html
This blocks me because i want to use ember-cli-deploy, but the dist/index.html file did not change.
Ember-cli-deploy make a checksum of the dist/index.html to generate a new deploy.
So I am forced to make a change in a js file to have a different checksum in the dist/index.html.

Is it normal that hbs files are ignored for checksums?
Thanks for writing this addon and your help.

**Comment by rickharrison** [comment]
Each file has its own checksum attached to it. There is no need for the checksum to change if the contents of the file do not change.

**Comment by rduque1** [comment]
The content of the file changed but the checksum did not. But today is working properly, so I must had something wrong in my workspace. Sorry for the bothering and thanks again.
