### ISSUE TITLE
manifest.json without digest

### ISSUE THREAD

**Issue by elucid** [rickharrison/broccoli-asset-rev#38]
We run a fork of broccoli-asset-rev so that we can avoid fingerprinting the generated `manifest.json` file. I was going to open a PR with this change but from reading the repo history noticed this is how it originally worked and that broccoli-asset-rev was later updated to support what Heroku expects.

https://devcenter.heroku.com/articles/rails-asset-pipeline#compiling-assets-locally seems to suggest that both `manifest.json` and `manifest-<hash>.json` should be supported but I assume this is not the case based on the original commit. We don't deploy to Heroku so I can't verify without some testing.

Our use case is a little different. We generate the manifest file so that other applications in our ecosystem can parse it and generate fingerprinted links to assets in the ember app. Having a fixed filename for the manifest makes sense for this case. Additionally, the manifest is never served publicly or cached so having it fingerprinted is of no value from that perspective.

If this seems like a reasonable use case to support, could I open a PR to support conditionally enabling/disabling fingerprinting the manifest file?

**Comment by rickharrison** [comment]
Could using the `exclude` property solve this?

**Comment by elucid** [comment]
I don't beliefe having it in the exclude list gets picked up. Perhaps that should be the fix...

**Comment by rickharrison** [comment]
Yea, I think that would be the preferable solution.

**Comment by elucid** [comment]
Ok no problem. PR incoming

**Comment by rickharrison** [comment]
I'm going to close this for now since a PR is currently open.
