### ISSUE TITLE
Use latest version of broccoli-asset-rewrite

### ISSUE THREAD

**Issue by tdesmet** [rickharrison/broccoli-asset-rev#40]
The latest version of broccoli-asset-rewrite is 1.0.4 and has a fix for https://github.com/rickharrison/broccoli-asset-rewrite/issues/11

could you update this package to tuse the latest version?

**Comment by rickharrison** [comment]
Yes, I will do that, but if you npm install it will grab the latest version of asset-rewrite due to how semver works.
