### ISSUE TITLE
Feature request: allow prepend but disable hash

### ISSUE THREAD

**Issue by Truffula** [rickharrison/broccoli-asset-rev#49]
I'm using broccoli-asset-rev to create a build be placed in versioned folder (for use with ember-cli-deploy) and which will be deployed on multiple servers, so I'd like to be able to use the prepend functionality for adding the hostname, but not add hashes to the end of files. If customHash returns empty string or null, I still get a hyphen appended, or `-null` respectively. It would be helpful if the hyphen was only added if `customHash` returned a non-empty string.

**Comment by rickharrison** [comment]
I think this could be fixed by doing something like `if (this.hasOwnProperty('customHash')`.

Would you mind testing it out and submitting a PR?

**Comment by Truffula** [comment]
Will see what I can do!

**Comment by chrislopresto** [comment]
We need something similar. We are simulating production environment asset hosting in dev. We want to prepend a different fqdn without appending a hash (for dev only).

@rickharrison Would you be open to a new config option to disable the hash? Something like `hashEnabled` defaulted to `true`. In our case, we could then set this to `false` in dev.

Thoughts?

**Comment by rickharrison** [comment]
I'd like to accomplish this by providing null as the `customHash`. A PR would be great to accomplish this.

**Comment by chrislopresto** [comment]
Sounds good.

**Comment by calebboyd** [comment]
I submitted a PR for this. It seems to help significantly for build/rebuild time in dev environments (setup as @chrislopresto explained).

**Comment by rickharrison** [comment]
Added in `2.0.4`

**Comment by chrislopresto** [comment]
Works like a charm. Thanks @calebboyd @rickharrison

**Comment by chrislopresto** [comment]
@calebboyd @rickharrison FYI, we came across a problem in broccoli-asset-rewrite. It wasn't respecting the prepend option for our source maps in the dev config I mentioned here. Just put up this PR: https://github.com/rickharrison/broccoli-asset-rewrite/pull/17

**Comment by calebboyd** [comment]
Hah, nice find. That helps me out too!
