### ISSUE TITLE
pass file name to customHash function?

### ISSUE THREAD

**Issue by kbullaughey** [rickharrison/broccoli-asset-rev#57]
I found a handy use for customHash, which is to force a hard-reset of the hashes. My use case was wanting to invalidate cloud-front caches so that I could get new Origin headers necessary for a domain name change. By defining a customHash function that just added an extra version string to the end of the content and then doing the usual md5 hash, I now have a way to force a hard-reset of all hashes by incrementing this version. 

However, it would be nice if the file name was also passed to the customHash function so that one could more intelligently decide how to hash the content. In my use case, this would allow me to only reset the cache for a certain file or subset of files.

Would this be a straightforward fix. Is there appetite for it?

**Comment by briangonzalez** [comment]
Simple: https://github.com/rickharrison/broccoli-asset-rev/pull/58

**Comment by kbullaughey** [comment]
Great!
