### ISSUE TITLE
Add bypassFingerprinting option; useful when only prepending is needed

### ISSUE THREAD

**Issue by briangonzalez** [rickharrison/broccoli-asset-rev#59]

**Comment by rickharrison** [comment]
I believe this is possible from #52

**Comment by briangonzalez** [comment]
@rickharrison It is not.

There is nothing I can do in `customHash` to make that `-` not appear in my file names.

**Comment by rickharrison** [comment]
You need to set it to `null`. We even have a test verifying this behavior.

**Comment by briangonzalez** [comment]
You're right. Thanks for the clarification.

**Comment by rickharrison** [comment]
We probably need better documentation around this. Any help with adding docs via a PR would be greatly appreciated :)
