### ISSUE TITLE
hashing may be funky

### ISSUE THREAD

**Issue by stefanpenner** [rickharrison/broccoli-asset-rev#70]
https://github.com/rickharrison/broccoli-asset-rev/blob/master/lib/fingerprint.js#L81
is from: https://github.com/rickharrison/broccoli-asset-rev/blob/master/lib/fingerprint.js#L35
which is: https://github.com/rickharrison/broccoli-asset-rev/blob/master/lib/fingerprint.js#L181

but `md5hash` takes only 1 arg, but https://github.com/rickharrison/broccoli-asset-rev/blob/master/lib/fingerprint.js#L81 passes two, the second arg is lost.

we likely want:

```js
var hash = this.hashFn(file + '\x00' + tmpPath);
```

or to remove the second arg, or leave a comment explaining this was the intent (if the default functionality is to ignore the path, but the custom hashFn could use it)

**Comment by rickharrison** [comment]
That argument is only there for users who want to have a custom hash function. The default md5 implementation doesn't use it. It is from #58

**Comment by stefanpenner** [comment]
Sounds good. It should likely be commented, i can submit a pr later this weekend
