### ISSUE TITLE
Is there a way to prepend and fingerprint js and css files but only prepend image files?

### ISSUE THREAD

**Issue by dravecza** [rickharrison/broccoli-asset-rev#81]
Hi there,

we are working on a project where we host our Ember app on a CDN with loads of images which are rarely modified, thus we want them not to be fingerprinted, but prepended. On the other hand, the code is pretty much alive with loads of fixes, new features, etc, thus we want them to be fingerprinted with each new release.
Am I seeing it right that currently there is no way to have this dual functionality?

**Comment by rickharrison** [comment]
That is correct. Why do you not what your images to be fingerprinted? If they don't change, they will receive the same fingerprint every time and then thus can be cached.

**Comment by dravecza** [comment]
Oh, I see! Thanks for clarifying it for me, I had some misconceptions about it.
Then I think nothing to do here, I'm closing the issue.
