### ISSUE TITLE
Git tags missing 

### ISSUE THREAD

**Issue by Turbo87** [rickharrison/broccoli-asset-rev#97]
It would be awesome if you could add the missing git tags corresponding with the releases to this repo. That would make it much easier to see which commits are included in which releases. Thanks :)

**Comment by Turbo87** [comment]
@rickharrison any comments?

**Comment by rickharrison** [comment]
The commits are easily viewable in the commit log

**Comment by Turbo87** [comment]
@rickharrison I'm talking about git tags, not commit. Those that would show up at https://github.com/rickharrison/broccoli-asset-rev/tags
