### ISSUE TITLE
Regression in broccoli-asset-rewrite breaks asset URLs

### ISSUE THREAD

**Issue by mjuniper** [rickharrison/broccoli-asset-rev#98]
See https://github.com/rickharrison/broccoli-asset-rewrite/issues/36

Perhaps you could revlock the broccoli-asset-rewrite dependency to v1.0.11?

**Comment by rickharrison** [comment]
Going to close this as the issue is in rewrite. A failing test case would greatly help!

**Comment by mjuniper** [comment]
👍
